# Generated by Django 5.1.6 on 2025-09-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_app", "0003_userprofile_delete_login_jobapplication_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "next_action",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
