# Generated by Django 5.2.6 on 2025-09-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0008_remove_resume_education_remove_resume_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='Untitled Resume', max_length=255),
        ),
    ]
